# @fileName: credentials.py
# @creation_date: 18/09/2024
# @authors: averyark

""" Note: This description is generated by Copilot
This module provides functions to validate and set user credentials using an SQLite database.
"""
import sqlite3
from icecream import ic

credentialsPath = "mock-database.db"
db = sqlite3.connect(credentialsPath)
cursor = db.cursor()

def validate_credentials(userId: str, input: str):
    if str(userId) == None or str(input) == None:
        return False

    cursor.execute(
        f'''
            SELECT DISTINCT password FROM Credentials WHERE userId IS '{userId}'
        '''
    )
    row = cursor.fetchone()

    ic(row)

    if row and row[0] == input:
        return True
    else:
        return False

def set_credentials(userId: int, password: str):
    cursor.execute(
        f'''
            INSERT INTO Credentials(
                id, userId, password
            ) VALUES (
                NULL, '{userId}', '{password}'
            )
        '''
    )
    db.commit()
