# @fileName: signup.py
# @creation_date: 14/09/2024
# @authors: averyark

""" Note: This description is generated by Copilot
This module handles the signup process for new users. It includes functions to validate user data, check for existing users, and insert new user data into a SQLite database. Additionally, it sets user credentials upon successful signup.
"""

from icecream import ic

from .user import User, validate_user_data
from .credentials import set_credentials

import sqlite3
credentialsPath = 'mock-database.db'
db = sqlite3.connect(credentialsPath)
cursor = db.cursor()

def signup(data: dict, permission: int) -> User:
    validate_user_data(data)

    cursor.execute(
        f'''
            SELECT DISTINCT * FROM Userdata WHERE email IS '{data.get("email")}'
        '''
    )
    row = cursor.fetchone()

    if row:
        raise LookupError("This email already exist in the database")

    try:
        cursor.execute(
            f'''
                INSERT INTO Userdata(
                    id, email, firstName, lastName, birthday, permission
                ) VALUES (
                    NULL,
                    '{data.get('email')}',
                    '{data.get('firstName')}',
                    '{data.get('lastName')}',
                    '{data.get('birthday')}',
                    {permission}
                )
            '''
        )

        # obtain the userId
        cursor.execute(
            f'''
                SELECT DISTINCT id FROM Userdata WHERE email IS '{data.get('email')}'
            '''
        )

        row = cursor.fetchone()

        if row:
            db.commit()
            set_credentials(row[0], data.get('password'))
        else:
            # wait what?
            db.rollback()
    except Exception as err:
        # rollback potential changes that are performed before point o f error
        db.rollback()
        # and raise error
        raise Exception(err)
